import { z } from "zod/mini";
import type { AppData } from "../../types";

const id = z.string().check(z.minLength(1));
const text = z.string();
const finiteNumber = z.number();
const nullableFiniteNumber = z.nullable(finiteNumber);

const role = z.enum(["CAJERO", "ENCARGADO", "ADMINISTRADOR"]);
const movementStatus = z.enum(["ACTIVO", "ANULADO"]);
const currency = z.literal("UYU");
const financialMedium = z.enum(["EFECTIVO", "BANCO"]);
const partner = z.enum(["RICARDO", "MATHIAS"]);
const salaryType = z.enum(["MENSUAL", "JORNAL", "HORA"]);
const salaryConcept = z.enum([
  "SALARIO",
  "SUELDO",
  "ADELANTO",
  "EXTRA",
  "HORAS_EXTRAS",
  "AJUSTE",
  "DESCUENTO",
  "AGUINALDO",
  "SALARIO_VACACIONAL",
]);
const salarySettlementOrigin = z.enum(["CAJA", "LIQUIDACION"]);

const storedFileMetaSchema = z.strictObject({
  name: text,
  type: text,
  size: finiteNumber,
  uploadedAt: text,
});

const userSchema = z.strictObject({
  id,
  name: text,
  username: text,
  password: text,
  role,
  status: z.enum(["ACTIVO", "INACTIVO"]),
  localIds: z.array(id),
});

const localSchema = z.strictObject({
  id,
  name: text,
  tenantName: text,
  phone: text,
  email: text,
  address: text,
  googleMapsUrl: text,
  images: z.array(
    z.strictObject({
      id,
      name: text,
      dataUrl: text,
      createdAt: text,
    }),
  ),
  status: z.enum(["ACTIVO", "INACTIVO", "CERRADO"]),
});

const staffScheduleSchema = z.strictObject({
  day: z.enum(["LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO"]),
  start: text,
  end: text,
  rest: z.boolean(),
});

const staffSchema = z.strictObject({
  id,
  visibleId: text,
  firstName: text,
  lastName: text,
  documentId: text,
  address: text,
  phone: text,
  email: text,
  birthDate: text,
  hireDate: text,
  position: text,
  localId: id,
  salaryType,
  nominalSalary: finiteNumber,
  salaryAdvanceBalance: finiteNumber,
  vacationDays: finiteNumber,
  usedVacationDays: finiteNumber,
  estimatedAguinaldo: finiteNumber,
  estimatedVacationSalary: finiteNumber,
  emergencyContact: text,
  bankAccount: text,
  schedule: z.array(staffScheduleSchema),
  notes: text,
  status: z.enum(["ACTIVO", "BAJA", "PAPELERA"]),
  createdAt: text,
  updatedAt: text,
  terminatedAt: z.optional(text),
  deletedAt: z.optional(text),
});

const salarySettlementSchema = z.strictObject({
  id,
  period: text,
  balanceId: z.optional(id),
  staffId: id,
  staffName: text,
  localId: id,
  paymentAccountId: z.optional(id),
  currency: z.optional(currency),
  baseSalary: finiteNumber,
  advances: finiteNumber,
  extraAmount: finiteNumber,
  extraConcept: text,
  aguinaldo: finiteNumber,
  vacationSalary: finiteNumber,
  otherDeductions: finiteNumber,
  totalToPay: finiteNumber,
  concept: salaryConcept,
  notes: text,
  status: z.enum(["BORRADOR", "CONFIRMADA", "ANULADA"]),
  origin: z.optional(salarySettlementOrigin),
  createdBy: z.optional(id),
  createdByName: z.optional(text),
  approvedBy: z.optional(id),
  approvedByName: z.optional(text),
  approvedAt: z.optional(text),
  annulledBy: z.optional(id),
  annulledByName: z.optional(text),
  annulledAt: z.optional(text),
  correctionClosureId: z.optional(id),
  annulledInCorrectionClosureId: z.optional(id),
  createdAt: text,
  updatedAt: text,
});

const salaryHistorySchema = z.strictObject({
  id,
  staffId: id,
  staffName: text,
  localId: id,
  previousSalaryType: salaryType,
  newSalaryType: salaryType,
  previousNominalSalary: finiteNumber,
  newNominalSalary: finiteNumber,
  effectiveDate: text,
  reason: text,
  userId: id,
  userName: text,
  createdAt: text,
});

const salaryClosureSettlementSnapshotSchema = z.strictObject({
  id,
  concept: salaryConcept,
  amount: finiteNumber,
  notes: text,
  origin: salarySettlementOrigin,
  createdByName: text,
  approvedByName: text,
  createdAt: text,
});

const salaryClosureEmployeeSnapshotSchema = z.strictObject({
  staffId: id,
  staffName: text,
  position: text,
  localId: id,
  salaryType,
  baseSalary: finiteNumber,
  salaryPaid: finiteNumber,
  advances: finiteNumber,
  extraAmount: finiteNumber,
  bonuses: finiteNumber,
  deductions: finiteNumber,
  totalAmount: finiteNumber,
  baseCoveredAmount: finiteNumber,
  liquidatedAmount: finiteNumber,
  pendingAmount: finiteNumber,
  settlementIds: z.array(id),
  settlements: z.array(salaryClosureSettlementSnapshotSchema),
});

const salaryClosureSchema = z.strictObject({
  id,
  visibleId: text,
  period: text,
  startDate: text,
  endDate: text,
  periodLabel: text,
  kind: z.enum(["ORDINARIO", "CORRECTIVO"]),
  revision: finiteNumber,
  parentClosureId: z.optional(id),
  snapshotVersion: finiteNumber,
  employeeSnapshots: z.array(salaryClosureEmployeeSnapshotSchema),
  employeeCount: finiteNumber,
  settlementIds: z.array(id),
  totalBase: finiteNumber,
  totalExtras: finiteNumber,
  totalBonuses: finiteNumber,
  totalDeductions: finiteNumber,
  totalSalaries: finiteNumber,
  totalSalaryPaid: finiteNumber,
  totalAdvances: finiteNumber,
  totalBaseCovered: finiteNumber,
  totalLiquidated: finiteNumber,
  totalPending: finiteNumber,
  status: z.enum(["CORRECCION_ABIERTA", "CERRADO", "ANULADO"]),
  note: text,
  createdBy: id,
  createdByName: text,
  createdAt: text,
  closedBy: z.optional(id),
  closedByName: z.optional(text),
  closedAt: z.optional(text),
});

const clientSchema = z.strictObject({
  id,
  visibleId: text,
  name: text,
  documentType: z.enum(["CEDULA", "PASAPORTE"]),
  documentId: text,
  photoFile: z.optional(storedFileMetaSchema),
  identityDocumentFile: z.optional(storedFileMetaSchema),
  phone: text,
  email: text,
  address: text,
  birthDate: text,
  localId: id,
  category: z.enum(["GENERAL", "FRECUENTE", "VIP"]),
  notes: text,
  status: z.enum(["ACTIVO", "INACTIVO", "PAPELERA"]),
  createdAt: text,
  updatedAt: text,
  deletedAt: z.optional(text),
});

const currentAccountSchema = z.strictObject({
  id,
  kind: z.enum([
    "PERSONAL",
    "TRANSFERENCIAS",
    "LOCAL_EFECTIVO",
    "LOCAL_BANCO",
    "PRINCIPAL_EFECTIVO",
    "PRINCIPAL_BANCO",
    "SOCIO",
  ]),
  entityId: z.optional(id),
  name: text,
  currency,
  status: z.enum(["ACTIVA", "INACTIVA"]),
  createdAt: text,
  updatedAt: text,
});

const accountMovementSchema = z.strictObject({
  id,
  accountId: id,
  localId: z.optional(id),
  balanceId: z.optional(id),
  sourceType: z.enum([
    "SUELDO",
    "TRANSFERENCIA",
    "GASTO",
    "REGALO",
    "RETIRO",
    "APORTE",
    "TRASPASO_CAJA",
    "APORTE_SOCIO",
    "RETIRO_SOCIO",
    "RESULTADO_MAQUINAS",
    "DIFERENCIA_CAJA",
    "MIGRACION",
    "AJUSTE",
  ]),
  sourceId: id,
  direction: z.enum(["ENTRADA", "SALIDA"]),
  concept: text,
  amount: finiteNumber,
  currency,
  detail: text,
  status: movementStatus,
  userId: id,
  createdAt: text,
  reversalOf: z.optional(id),
  previousAdjustmentId: z.optional(id),
});

const capitalMovementSchema = z.strictObject({
  id,
  balanceId: id,
  localId: id,
  type: z.enum(["RETIRO", "APORTE"]),
  medium: z.enum(["EFECTIVO", "TRANSFERENCIA"]),
  timing: z.enum(["APERTURA", "OPERATIVO", "CIERRE"]),
  person: partner,
  amount: finiteNumber,
  note: text,
  status: movementStatus,
  userId: id,
  createdAt: text,
});

const treasuryTransferSchema = z.strictObject({
  id,
  balanceId: z.optional(id),
  localId: id,
  type: z.enum(["RETIRO_CAJA", "APORTE_CAJA"]),
  medium: financialMedium,
  timing: z.enum(["APERTURA", "OPERATIVO", "CIERRE"]),
  amount: finiteNumber,
  currency,
  note: text,
  status: movementStatus,
  userId: id,
  createdAt: text,
});

const partnerMovementSchema = z.strictObject({
  id,
  balanceId: z.optional(id),
  localId: id,
  partner,
  type: z.enum(["APORTE_SOCIO", "RETIRO_SOCIO"]),
  medium: financialMedium,
  amount: finiteNumber,
  currency,
  note: text,
  status: movementStatus,
  userId: id,
  createdAt: text,
});

const machineSchema = z.strictObject({
  id,
  visibleId: text,
  name: text,
  localId: id,
  location: text,
  lastIn: finiteNumber,
  lastOut: finiteNumber,
  status: z.enum(["ACTIVA", "INACTIVA", "MANTENIMIENTO", "DESUSO"]),
  notes: text,
});

const balanceSchema = z.strictObject({
  id,
  visibleId: z.optional(text),
  localId: id,
  operatingDate: text,
  status: z.enum(["EN_PROCESO", "CERRADO", "AJUSTADO", "ANULADO"]),
  initialFund: finiteNumber,
  initialBankFund: z.optional(finiteNumber),
  initialNote: text,
  openedBy: id,
  openedByRole: z.optional(role),
  openedAt: text,
  closedBy: z.optional(id),
  closedByRole: z.optional(role),
  closedAt: z.optional(text),
  declaredCash: z.optional(finiteNumber),
  declaredBank: z.optional(finiteNumber),
  nextBase: z.optional(finiteNumber),
  nextBankBase: z.optional(finiteNumber),
  withdrawal: z.optional(finiteNumber),
  finalWithdrawalCash: z.optional(finiteNumber),
  finalWithdrawalBank: z.optional(finiteNumber),
  finalTransferToPrincipalCash: z.optional(finiteNumber),
  finalTransferToPrincipalBank: z.optional(finiteNumber),
  cashDifference: z.optional(finiteNumber),
  bankDifference: z.optional(finiteNumber),
  differenceNote: z.optional(text),
  differenceStatus: z.optional(z.enum(["PENDIENTE", "VERIFICADA", "CORREGIDA", "ANULADA"])),
  differenceReviewedBy: z.optional(id),
  differenceReviewedAt: z.optional(text),
  differenceReviewNote: z.optional(text),
});

const readingSchema = z.strictObject({
  id,
  balanceId: id,
  machineId: id,
  inPrevious: finiteNumber,
  inActual: nullableFiniteNumber,
  outPrevious: finiteNumber,
  outActual: nullableFiniteNumber,
  result: finiteNumber,
  status: z.enum(["PENDIENTE", "CARGADA", "SIN_LECTURA", "FUERA_DE_SERVICIO"]),
  observation: text,
  updatedBy: id,
  updatedAt: text,
});

const expenseSchema = z.strictObject({
  id,
  balanceId: z.optional(id),
  localId: id,
  paymentAccountId: id,
  currency,
  category: text,
  subcategory: text,
  amount: finiteNumber,
  description: text,
  receipt: text,
  receiptFileName: z.optional(text),
  receiptFileType: z.optional(text),
  receiptDataUrl: z.optional(text),
  status: movementStatus,
  reviewStatus: z.optional(z.enum(["PENDIENTE", "REVISADO", "OBSERVADO"])),
  reviewedBy: z.optional(id),
  reviewedAt: z.optional(text),
  reviewNote: z.optional(text),
  userId: id,
  createdAt: text,
});

const periodicClosureSchema = z.strictObject({
  id,
  visibleId: text,
  localId: id,
  type: z.enum(["SEMANAL", "QUINCENAL", "MENSUAL", "PERSONALIZADO"]),
  startDate: text,
  endDate: text,
  balanceIds: z.array(id),
  principalExpenseIds: z.array(id),
  principalSalarySettlementIds: z.array(id),
  treasuryTransferIds: z.array(id),
  partnerMovementIds: z.array(id),
  resultMachines: finiteNumber,
  totalExpenses: finiteNumber,
  totalSalaries: finiteNumber,
  totalGifts: finiteNumber,
  totalOutflows: finiteNumber,
  commercialResult: finiteNumber,
  totalTransfers: finiteNumber,
  totalWithdrawals: finiteNumber,
  totalContributions: finiteNumber,
  totalCajaToPrincipal: finiteNumber,
  totalPrincipalToCaja: finiteNumber,
  totalPartnerContributions: finiteNumber,
  totalPartnerWithdrawals: finiteNumber,
  cashDifference: finiteNumber,
  bankDifference: finiteNumber,
  pendingDifferences: finiteNumber,
  status: z.enum(["GENERADO", "ANULADO"]),
  note: text,
  createdBy: id,
  createdAt: text,
});

const expenseCategorySchema = z.strictObject({
  id,
  name: text,
  subcategories: z.array(text),
  status: z.enum(["ACTIVA", "INACTIVA"]),
});

const transferSchema = z.strictObject({
  id,
  balanceId: id,
  clientId: z.optional(id),
  receipt: text,
  name: text,
  amount: finiteNumber,
  account: text,
  status: movementStatus,
  userId: id,
  createdAt: text,
});

const giftSchema = z.strictObject({
  id,
  balanceId: id,
  clientId: z.optional(id),
  clientIds: z.optional(z.array(id)),
  type: z.enum(["EFECTIVO", "CREDITO", "MIXTO"]),
  cashAmount: finiteNumber,
  creditAmount: finiteNumber,
  reference: text,
  description: text,
  status: movementStatus,
  userId: id,
  createdAt: text,
});

const auditEventSchema = z.strictObject({
  id,
  userId: id,
  userName: text,
  actualRole: z.optional(role),
  actorRole: z.optional(role),
  action: text,
  entity: text,
  entityId: id,
  localId: z.optional(id),
  localIds: z.optional(z.array(id)),
  previousValue: text,
  newValue: text,
  reason: text,
  createdAt: text,
});

const machineLocalHistorySchema = z.strictObject({
  id,
  machineId: id,
  machineVisibleId: text,
  machineName: text,
  localId: id,
  action: z.enum(["AGREGADA", "MODIFICADA", "MOVIDA", "QUITADA", "CONTADORES", "RESET"]),
  detail: text,
  createdAt: text,
  userId: id,
});

export const appDataSchema = z.strictObject({
  users: z.array(userSchema),
  staff: z.array(staffSchema),
  salarySettlements: z.array(salarySettlementSchema),
  salaryHistories: z.array(salaryHistorySchema),
  salaryClosures: z.array(salaryClosureSchema),
  clients: z.array(clientSchema),
  periodicClosures: z.array(periodicClosureSchema),
  currentAccounts: z.array(currentAccountSchema),
  accountMovements: z.array(accountMovementSchema),
  capitalMovements: z.array(capitalMovementSchema),
  treasuryTransfers: z.array(treasuryTransferSchema),
  partnerMovements: z.array(partnerMovementSchema),
  locals: z.array(localSchema),
  machines: z.array(machineSchema),
  balances: z.array(balanceSchema),
  readings: z.array(readingSchema),
  expenseCategories: z.array(expenseCategorySchema),
  expenses: z.array(expenseSchema),
  transfers: z.array(transferSchema),
  gifts: z.array(giftSchema),
  audit: z.array(auditEventSchema),
  machineLocalHistory: z.array(machineLocalHistorySchema),
}) satisfies z.ZodMiniType<AppData>;
